font:
  normal:
    # family: Monaco Nerd Font Mono
    # family: agave Nerd Font Mono
    # family: Hack Nerd Font Mono
    # family: InconsolataLGC Nerd Font Mono
    # family: BitstreamVeraSansMono Nerd Font Mono
    family: CodeNewRoman Nerd Font Mono
    # family: mononoki Nerd Font
    # family: CaskaydiaCove Nerd Font
    # style: Regular

  bold:
    family: CodeNewRoman Nerd Font Mono

  italic:
    family: mononoki Nerd Font

  size: 14.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 5

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

# 背景半透明，方便抄代码
background_opacity: 0.8

window_opacity: 0.5

# 实时重载配置文件，不用重启测试配置选项
live_config_reload: true

env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use 'alacritty' if it is
  # available, otherwise 'xterm-256color' is used.
  TERM: xterm-256color

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is not scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 0
    y: 0

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  decorations: full

# 配色方案
# Colors (Ayu Mirage)
# colors:
# # Default colors
# primary:
# background: '#202734'
# foreground: '#CBCCC6'
# # Normal colors
# normal:
# black: '#191E2A'
# red: '#FF3333'
# green: '#BAE67E'
# yellow: '#FFA759'
# blue: '#73D0FF'
# magenta: '#FFD580'
# cyan: '#95E6CB'
# white: '#C7C7C7'
# # Bright colors
# bright:
# black: '#686868'
# red: '#F27983'
# green: '#A6CC70'
# yellow: '#FFCC66'
# blue: '#5CCFE6'
# magenta: '#FFEE99'
# cyan: '#95E6CB'
# white: '#FFFFFF'

# dracula
colors:
  # Default colors
  primary:
    background: '#2c2c2c'
    foreground: '#d6d6d6'

    dim_foreground: '#dbdbdb'
    bright_foreground: '#d9d9d9'
    dim_background: '#202020' # not sure
    bright_background: '#3a3a3a' # not sure

  # Cursor colors
  cursor:
    text: '#2c2c2c'
    cursor: '#d9d9d9'

  # Normal colors
  normal:
    black: '#1c1c1c'
    red: '#bc5653'
    green: '#909d63'
    yellow: '#ebc17a'
    blue: '#7eaac7'
    magenta: '#aa6292'
    cyan: '#86d3ce'
    white: '#cacaca'

  # Bright colors
  bright:
    black: '#636363'
    red: '#bc5653'
    green: '#909d63'
    yellow: '#ebc17a'
    blue: '#7eaac7'
    magenta: '#aa6292'
    cyan: '#86d3ce'
    white: '#f7f7f7'

  # Dim colors
  dim:
    black: '#232323'
    red: '#74423f'
    green: '#5e6547'
    yellow: '#8b7653'
    blue: '#556b79'
    magenta: '#6e4962'
    cyan: '#5c8482'
    white: '#828282'

key_bindings:
  - { key: Back, action: ReceiveChar }
