font:
  normal:
    family: AurulentSansM Nerd Font
    style: Regular

  bold:
    family: AurulentSansM Nerd Font

  italic:
    family: AurulentSansM Nerd Font

  size: 16

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

# 实时重载配置文件，不用重启测试配置选项
live_config_reload: true

save_to_clipboard: true

key_bindings:
  - { key: V, mods: Command, action: Paste }
  - { key: C, mods: Command, action: Copy }

env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use 'alacritty' if it is
  # available, otherwise 'xterm-256color' is used.
  TERM: xterm-256color

window:
  opacity: 1
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 0
    lines: 0

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is not scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 0
    y: 0

  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  decorations: full

colors:
  name: astromouse
  author: ''
  primary:
    background: '#000000'
    foreground: '#ffffff'
  cursor:
    text: '#000000'
    cursor: '#ffffff'
  normal:
    black: '#1c1c1c'
    red: '#d770af'
    green: '#9acc79'
    yellow: '#d0d26b'
    blue: '#77b6c5'
    magenta: '#a488d9'
    cyan: '#7fcab3'
    white: '#8d8d8d'
  bright:
    black: '#3d3a3a'
    red: '#d28abf'
    green: '#8fb676'
    yellow: '#c8bc45'
    blue: '#8fa7b9'
    magenta: '#bd89de'
    cyan: '#6ec2a8'
    white: '#dad3d3'
